services:
  backend:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: dev
    container_name: "faynoSync_backend"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      s3:
        condition: service_healthy
    networks:
      - faynosync_network
    ports:
      - "9000:9000"
    volumes:
      -  ../envs/backend.env:/app/.env
      - ../../tuf_keys/:/app/tuf_keys/
