services:
  db:
    image: mongo:7.0.12
    container_name: "faynoSync_db"
    restart: always
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cb_faynosync_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=MheCk6sSKB1m4xKNw5I
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - faynosync_network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
